#!/usr/bin/env bash
for repo in ./apps/* ./packages/*; do
  name=$(basename $repo)
  if [[ "$#" -gt 0 ]]; then
    prefix=$1
    remote="git@github.com:$prefix/$name.git"
    git remote add $prefix-$name $remote
  else
    remote="git@github.com:feedhenry-raincatcher/$name.git"
    git remote add $name $remote
  fi
done
git remote -v