#!/bin/bash
if (( "$#" < 1 ))
then
  echo 'Usage: pr [packages|apps]/module <<base-branch>> <<remote-prefix>>'
  echo 'supply <<base-branch>> to specify the name of the branch to use as base (source) of the pull request, defaults to the current checked-out branch name'
  echo 'supply <<remote-prefix>> if you want to push to a conventionally-named remote like {my-fork}-raincatcher-demo-cloud'
  exit 1
fi
repo=$(basename $1)
currBranch=$(git symbolic-ref --short HEAD)
remoteOwner=${3:-feedhenry-raincatcher}
currBranch=$(git symbolic-ref --short HEAD)
baseBranch=${2:-$currBranch}
hub pull-request -o -b feedhenry-raincatcher/$repo:master -h $remoteOwner/$repo:$baseBranch
