#!/bin/bash
if (( "$#" < 1 ))
then
  echo 'Usage: push [packages|apps]/module <<remote-gitref>> <<remote-prefix>>'
  echo 'supply <<remote-prefix>> if you want to push to a conventionally-named remote like {my-fork}-raincatcher-demo-cloud'
  exit 1
fi
subtreePrefix=$1
repo=$(basename $1)
remotePrefix=$3
currBranch=$(git symbolic-ref --short HEAD)
remoteRef=${2:-$currBranch}
git subtree push --prefix=$subtreePrefix $3$repo $remoteRef